name: Build Anko
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9123335
        
      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Dependencies
        run: |
          mkdir -p dependencies
          ./download_dependencies.sh

      - name: Build
        run: |
          ./gradlew clean assembleRelease
          mkdir -p libs/anko
          find anko/library/generated/*/build/outputs/aar/*.aar -exec bash -c 'mv "$0" "libs/anko/$(basename "$0" | sed "s/-release\.aar$/.aar/")"' {} \;

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: anko
          path: libs/anko/*.aar
